apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: mycontainer
          image: nginx
